### ISSUE TITLE
Fails on v1?

### ISSUE THREAD

**Issue by OlegKunitsyn** [OtezVikentiy/symfony-jsonrpc-api-bundle#1]
```
    App\JsonRpcController\:
        resource: '../src/JsonRpcController/v1/{*Method.php}'
        tags:
            - { name: ov.rpc.method, namespace: App\JsonRpcController\v1\, version: 1 }
```
```
<?php

declare(strict_types=1);

namespace App\JsonRpcController\v1;

use App\Dto\EchoDto;
use OV\JsonRPCAPIBundle\Core\Annotation\JsonRPCAPI;

#[JsonRPCAPI(methodName: 'productEcho', type: 'POST')]
class JsonRpcProductEchoMethod
{
    public function call(EchoDto $dto): EchoDto
    {
        return $dto;
    }
}

```
Expected to find classApp\JsonRpcController\JsonRpcProductEchoMethod in file jsonrpc/src/JsonRpcController/v1/JsonRpcProductEchoMethod.php while importing services from resource ../src/JsonRpcController/v1/{*Method.php}, but it was not found!

**Comment by OtezVikentiy** [comment]
> ```
>     App\JsonRpcController\:
>         resource: '../src/JsonRpcController/v1/{*Method.php}'
>         tags:
>             - { name: ov.rpc.method, namespace: App\JsonRpcController\v1\, version: 1 }
> ```
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\JsonRpcController\v1;
> 
> use App\Dto\EchoDto;
> use OV\JsonRPCAPIBundle\Core\Annotation\JsonRPCAPI;
> 
> #[JsonRPCAPI(methodName: 'productEcho', type: 'POST')]
> class JsonRpcProductEchoMethod
> {
>     public function call(EchoDto $dto): EchoDto
>     {
>         return $dto;
>     }
> }
> ```
> 
> Expected to find classApp\JsonRpcController\JsonRpcProductEchoMethod in file jsonrpc/src/JsonRpcController/v1/JsonRpcProductEchoMethod.php while importing services from resource ../src/JsonRpcController/v1/{*Method.php}, but it was not found!




Hello! Thanks for the interest to my bundle!

Problem is that you should configure service.yaml this way:

>    App\JsonRpcController\v1\:
>       resource: '../src/JsonRpcController/v1/{*Method.php}'
>       tags:
>            - { name: ov.rpc.method, namespace: App\JsonRpcController\v1\, version: 1 }
