### ISSUE TITLE
Fails without version?

### ISSUE THREAD

**Issue by OlegKunitsyn** [OtezVikentiy/symfony-jsonrpc-api-bundle#2]
```
    App\JsonRpcController\:
        resource: '../src/JsonRpcController/{*Method.php}'
        tags:
            - { name: ov.rpc.method, namespace: App\JsonRpcController\ }
```

```
<?php

declare(strict_types=1);

namespace App\JsonRpcController;

use App\Dto\EchoDto;
use OV\JsonRPCAPIBundle\Core\Annotation\JsonRPCAPI;

#[JsonRPCAPI(methodName: 'productEcho', type: 'POST')]
class JsonRpcProductEchoMethod
{
    public function call(EchoDto $dto): EchoDto
    {
        return $dto;
    }
}
```

`{"jsonrpc":"2.0","error":{"code":0,"message":"App\\JsonRpcController\\JsonRpcProductEchoMethod::call(): Argument #1 ($dto) must be of type App\\Dto\\EchoDto, null given, called in \/vendor\/otezvikentiy\/json-rpc-api\/src\/Controller\/ApiController.php on line 133"},"id":"1"}`

**Comment by OtezVikentiy** [comment]
> ```
>     App\JsonRpcController\:
>         resource: '../src/JsonRpcController/{*Method.php}'
>         tags:
>             - { name: ov.rpc.method, namespace: App\JsonRpcController\ }
> ```
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\JsonRpcController;
> 
> use App\Dto\EchoDto;
> use OV\JsonRPCAPIBundle\Core\Annotation\JsonRPCAPI;
> 
> #[JsonRPCAPI(methodName: 'productEcho', type: 'POST')]
> class JsonRpcProductEchoMethod
> {
>     public function call(EchoDto $dto): EchoDto
>     {
>         return $dto;
>     }
> }
> ```
> 
> `{"jsonrpc":"2.0","error":{"code":0,"message":"App\\JsonRpcController\\JsonRpcProductEchoMethod::call(): Argument #1 ($dto) must be of type App\\Dto\\EchoDto, null given, called in \/vendor\/otezvikentiy\/json-rpc-api\/src\/Controller\/ApiController.php on line 133"},"id":"1"}`



This particular error can be resolved by simply renaming the $dto variable in $request. So far this is a bug in the code, but in general yes, it will need to be fixed.
